### ISSUE TITLE
Test8 Bug

### ISSUE THREAD

**Issue by rhamburg** [rhamburg/mcmc#1]
Bug issue when running test8 on master branch. Failed at step 54320 with the following error:

```
Traceback (most recent call last):
  File "master_mcmc.py", line 175, in <module>
    dl=dl, options=options, vol_arr=v_comov, kc=kcorr, plot_GRB=plot)
  File "/Users/rachelhamburg/Dropbox/FermiWork Team Folder/GradSchool/Dissertation/project/mcmc/simulation.py", line 104, in Simulation
    emax=detector.getfloat('nai_emax'), plotting=plot_GRB)
  File "/Users/rachelhamburg/Dropbox/FermiWork Team Folder/GradSchool/Dissertation/project/mcmc/source_functions.py", line 161, in Peak_flux
    idx_fov = random.random_integers(0, len(corr_pf)-1, num_fov)
  File "mtrand.pyx", line 1514, in mtrand.RandomState.random_integers
  File "mtrand.pyx", line 993, in mtrand.RandomState.randint
ValueError: low >= high
```

**Comment by rhamburg** [comment]
If the length of the corr_pf array (before the detector corrections) is 0, then I get this error. I'm fixing this by adding a check for the length of the corr_pf array. If the length is 0, then I return empty arrays which can be dealt with later on in the code. (I don't know how to attach/link the modified code to this, so I'll just make the change and reference this issue in the commit message.

```
   if len(corr_pf) > 0:
        STUFF HERE
        return corr_pf, final_pf
    else:
        return [], []
```
